"""
Report module for BBAT.
Aggregates results and generates Markdown/HTML reports using SQLite.
"""

import json
import os
from datetime import datetime
from typing import Dict, List

from modules.db import BBATDatabase


class ReportModule:
    """Generate human-readable reports from BBAT results."""

    def __init__(self, config: dict):
        self.config = config.get("reporting", {})
        self.formats = self.config.get("formats", ["json", "markdown"])
        self.db = BBATDatabase()

    def _db(self) -> BBATDatabase:
        return self.db

    def generate_markdown(self, results: Dict, target: str) -> str:
        """Generate a Markdown report from results."""
        lines = [
            f"# BBAT Scan Report",
            f"",
            f"**Target:** `{target}`",
            f"**Generated:** {datetime.utcnow().isoformat()}Z",
            f"",
            f"---",
            f"",
        ]

        target_id = self._db().get_target_id(target)

        # Recon stats from DB
        if target_id:
            stats = self._db().get_stats()
            lines.append("## Summary")
            lines.append(f"- Critical: {stats['critical']} | High: {stats['high']} | Medium: {stats['medium']} | Low: {stats['low']}")
            lines.append(f"- Endpoints: {stats['endpoints']} | Subdomains: {stats['subdomains']}")
            lines.append("")

            findings = self._db().get_findings(limit=50)
            if findings:
                lines.append("## Top Findings")
                for f in findings:
                    sev = f.get("severity", "info").upper()
                    lines.append(f"- **[{sev}]** {f.get('type')}: {f.get('description', '')[:200]}")
                lines.append("")

            subs = self._db().get_subdomains()[:20]
            if subs:
                lines.append("## Subdomains")
                for s in subs:
                    lines.append(f"- `{s}`")
                lines.append("")

            techs = self._db().get_technologies()[:20]
            if techs:
                lines.append("## Technologies")
                for t in techs:
                    lines.append(f"- {t['name']} ({t['category']}) [confidence: {t['confidence']}]")
                lines.append("")

        lines.append("---")
        lines.append("Report generated by BBAT v3.1.0")
        return "\n".join(lines)

    def generate_and_save(self, results: Dict, target: str, output_dir: str):
        """Generate reports in all configured formats and save them."""
        safe_target = os.path.basename(os.path.normpath(target)).replace(":", "_")
        for fmt in self.formats:
            if fmt == "markdown":
                content = self.generate_markdown(results, target)
                filepath = os.path.join(output_dir, f"report_{safe_target}.md")
                with open(filepath, "w", encoding="utf-8") as f:
                    f.write(content)
                print(f"[+] Markdown report saved to {filepath}")
            elif fmt == "html":
                content = self._md_to_html(self.generate_markdown(results, target), target)
                filepath = os.path.join(output_dir, f"report_{safe_target}.html")
                with open(filepath, "w", encoding="utf-8") as f:
                    f.write(content)
                print(f"[+] HTML report saved to {filepath}")

    def _md_to_html(self, md: str, target: str) -> str:
        """Simple markdown-to-HTML conversion."""
        html_lines = [
            "<!DOCTYPE html>",
            "<html><head><title>BBAT Report</title></head><body>",
            f"  <h1>BBAT Scan Report</h1>",
            f"  <p><strong>Target:</strong> {target}</p>",
            "  <hr>",
        ]
        for line in md.split("\n"):
            if line.startswith("## "):
                html_lines.append(f"  <h2>{line[3:]}</h2>")
            elif line.startswith("- "):
                html_lines.append(f"  <li>{line[2:]}</li>")
            else:
                html_lines.append(f"  <p>{line}</p>")
        html_lines.extend([
            "  <hr>",
            "  <p><em>Generated by BBAT v3.1.0</em></p>",
            "</body></html>",
        ])
        return "\n".join(html_lines)
