"""
WAFDetector module for BBAT.
Detects Web Application Firewalls via passive header inspection + active probing.
"""

import httpx
from typing import List, Dict
import re
from modules.utils import get_random_ua

WAF_SIGNATURES = [
    {"name": "Cloudflare", "headers": {"Server": r"cloudflare", "CF-RAY": r""}, "body": r"cloudflare|CF_", "type": "CDN/WAF"},
    {"name": "Akamai", "headers": {"Server": r"AkamaiGHost", "X-Akamai-Request-ID": r""}, "body": r"", "type": "CDN/WAF"},
    {"name": "AWS WAF", "headers": {"X-RateLimit-Limit": r""}, "body": r"AWS WAF|aws-waf", "type": "WAF"},
    {"name": "Imperva (Incapsula)", "headers": {"X-Iinfo": r"", "Set-Cookie": r"visid_incap"}, "body": r"incap_ses|incap_wl", "type": "WAF"},
    {"name": "Sucuri", "headers": {"Server": r"Sucuri/Cloudproxy", "X-Sucuri-ID": r""}, "body": r"Sucuri|Access Denied", "type": "WAF"},
    {"name": "Barracuda", "headers": {}, "body": r"Barracuda|barra_counter_session", "type": "WAF"},
    {"name": "F5 BIG-IP ASM", "headers": {"Server": r"BigIP", "X-WA-Result": r""}, "body": r"BigIP|F5 Networks", "type": "WAF"},
    {"name": "Fortinet FortiWeb", "headers": {"Server": r"FortiWeb"}, "body": r"", "type": "WAF"},
    {"name": "ModSecurity", "headers": {}, "body": r"Mod_Security|mod_security", "type": "WAF"},
    {"name": "Wordfence", "headers": {}, "body": r"wordfence|generated by Wordfence", "type": "WAF"},
    {"name": "SiteLock", "headers": {}, "body": r"Sitelock|SiteLock", "type": "WAF"},
    {"name": "Fastly", "headers": {"X-Served-By": r"cache", "X-Cache": r""}, "body": r"", "type": "CDN"},
    {"name": "Varnish", "headers": {"X-Varnish": r"", "Via": r"varnish"}, "body": r"", "type": "Cache"},
    {"name": "DOSarrest", "headers": {"X-DOSarrest-ID": r""}, "body": r"", "type": "WAF"},
    {"name": "StackPath", "headers": {"Server": r"StackPath", "X-Stack-CDN": r""}, "body": r"", "type": "WAF"},
    {"name": "Reblaze", "headers": {"Server": r"Reblaze"}, "body": r"", "type": "WAF"},
    {"name": "Palo Alto Next-Gen Firewall", "headers": {}, "body": r"Palo Alto|PA-series", "type": "WAF"},
    {"name": "Radware AppWall", "headers": {"X-SL-CompState": r"", "Server": r"AppWall"}, "body": r"", "type": "WAF"},
    {"name": "GreyWizard", "headers": {"X-GreyWizard-Block": r"", "X-GreyWizard-Protection": r""}, "body": r"", "type": "WAF"},
]

# Benign but suspicious payload triggers to validate WAF behavior
PROBE_PAYLOADS = [
    "/?id=' OR '1'='1",
    "/?search=<eval>alert(1)</eval>",
    "/?file=../../../etc/passwd",
    "/?redirect=https://evil.com",
]


class WAFDetectorModule:
    """Detects Web Application Firewalls from HTTP responses + active probing."""

    def __init__(self, config: dict):
        self.config = config.get("waf_detector", {})
        self.timeout = self.config.get("timeout", 10)
        self._ssl = config.get("recon", {}).get("ssl_verify", False)

    def _fetch(self, url: str) -> httpx.Response:
        return httpx.get(url, headers={"User-Agent": get_random_ua()}, timeout=self.timeout, verify=self._ssl, follow_redirects=False)

    def detect(self, target: str) -> List[Dict]:
        """Detect WAF/CDN for a given URL using passive + active probing."""
        from modules.utils import normalize_url
        url = normalize_url(target)
        findings = []

        try:
            # Passive header/body inspection
            resp = self._fetch(url)
            headers = {k.lower(): v for k, v in resp.headers.items()}
            body = resp.text

            for sig in WAF_SIGNATURES:
                detected = False
                confidence = "low"
                for header_key, pattern in sig["headers"].items():
                    header_value = headers.get(header_key.lower(), "")
                    if pattern and re.search(pattern, header_value, re.IGNORECASE):
                        detected = True
                        confidence = "high"
                    elif header_value and not pattern:
                        detected = True
                        confidence = "medium"
                if sig["body"] and re.search(sig["body"], body, re.IGNORECASE):
                    detected = True
                    confidence = "high"
                if detected:
                    findings.append({"waf": sig["name"], "type": sig["type"], "confidence": confidence, "url": url, "method": "passive"})

            # Active probing: compare benign vs probe responses
            if not findings:
                print(f"[*] Active WAF probing on {url}...")
                base_resp = self._fetch(url)
                for probe in PROBE_PAYLOADS:
                    probe_url = url.rstrip("/") + probe
                    try:
                        probe_resp = self._fetch(probe_url)
                        if base_resp.status_code != probe_resp.status_code or "blocked" in probe_resp.text.lower():
                            findings.append({
                                "waf": "Generic WAF (Active Probe)",
                                "type": "WAF",
                                "confidence": "medium",
                                "url": url,
                                "method": "active_probe",
                                "probe": probe,
                            })
                            break
                    except Exception:
                        continue
        except Exception:
            pass

        unique = []
        seen = set()
        for f in findings:
            key = (f["waf"], f["confidence"])
            if key not in seen:
                seen.add(key)
                unique.append(f)
        return unique

    def detect_batch(self, urls: List[str]) -> Dict:
        """Detect WAF/CDN for multiple URLs."""
        all_findings = []
        print(f"[*] Detecting WAF/CDN for {len(urls)} URLs...")
        for url in urls:
            findings = self.detect(url)
            all_findings.extend(findings)
        wafs = {f["waf"] for f in all_findings}
        types = {f["type"] for f in all_findings}
        print(f"[+] WAF detection complete. Detected {len(wafs)} unique WAFs/CDNs.")
        return {
            "urls_checked": len(urls),
            "wafs_detected": list(wafs),
            "types_detected": list(types),
            "findings": all_findings,
        }
