"""
WAFDetector module for BBAT.
Detects Web Application Firewalls by analyzing HTTP responses.
"""

import requests
import re
from typing import List, Dict
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# WAF signatures: header or body patterns
WAF_SIGNATURES = [
    {"name": "Cloudflare", "headers": {"Server": r"cloudflare", "CF-RAY": r""}, "body": r"cloudflare|CF_", "type": "CDN/WAF"},
    {"name": "Akamai", "headers": {"Server": r"AkamaiGHost", "X-Akamai-Request-ID": r""}, "body": r"", "type": "CDN/WAF"},
    {"name": "AWS WAF", "headers": {"X-RateLimit-Limit": r""}, "body": r"AWS WAF|aws-waf", "type": "WAF"},
    {"name": "Imperva (Incapsula)", "headers": {"X-Iinfo": r"", "Set-Cookie": r"visid_incap"}, "body": r"incap_ses|incap_wl", "type": "WAF"},
    {"name": "Sucuri", "headers": {"Server": r"Sucuri/Cloudproxy", "X-Sucuri-ID": r""}, "body": r"Sucuri|Access Denied", "type": "WAF"},
    {"name": "Barracuda", "headers": {}, "body": r"Barracuda|barra_counter_session", "type": "WAF"},
    {"name": "F5 BIG-IP ASM", "headers": {"Server": r"BigIP", "X-WA-Result": r""}, "body": r"BigIP|F5 Networks", "type": "WAF"},
    {"name": "Fortinet FortiWeb", "headers": {"Server": r"FortiWeb"}, "body": r"", "type": "WAF"},
    {"name": "ModSecurity", "headers": {}, "body": r"Mod_Security|mod_security", "type": "WAF"},
    {"name": "Wordfence", "headers": {}, "body": r"wordfence|generated by Wordfence", "type": "WAF"},
    {"name": "SiteLock", "headers": {}, "body": r"Sitelock|SiteLock", "type": "WAF"},
    {"name": "Fastly", "headers": {"X-Served-By": r"cache", "X-Cache": r""}, "body": r"", "type": "CDN"},
    {"name": "Varnish", "headers": {"X-Varnish": r"", "Via": r"varnish"}, "body": r"", "type": "Cache"},
    {"name": "DOSarrest", "headers": {"X-DOSarrest-ID": r""}, "body": r"", "type": "WAF"},
    {"name": "StackPath", "headers": {"Server": r"StackPath", "X-Stack-CDN": r""}, "body": r"", "type": "WAF"},
    {"name": "Reblaze", "headers": {"Server": r"Reblaze"}, "body": r"", "type": "WAF"},
    {"name": "Palo Alto Next-Gen Firewall", "headers": {}, "body": r"Palo Alto|PA-series", "type": "WAF"},
    {"name": "Radware AppWall", "headers": {"X-SL-CompState": r"", "Server": r"AppWall"}, "body": r"", "type": "WAF"},
    {"name": "GreyWizard", "headers": {"X-GreyWizard-Block": r"", "X-GreyWizard-Protection": r""}, "body": r"", "type": "WAF"},
    {"name": "ASP.NET Generic", "headers": {"X-AspNet-Version": r"", "X-AspNetMvc-Version": r""}, "body": r"", "type": "Framework"},
    {"name": "Kona Site Defender (Akamai)", "headers": {"Server": r"AkamaiGHost", "X-RateLimit-Limit": r""}, "body": r"", "type": "WAF"},
    {"name": "Astra", "headers": {}, "body": r"astra|astra security", "type": "WAF"},
    {"name": "Comodo", "headers": {}, "body": r"Protected by COMODO WAF", "type": "WAF"},
    {"name": "Juniper", "headers": {}, "body": r"Juniper Networks|Junos", "type": "WAF"},
    {"name": "NSFocus", "headers": {}, "body": r"NSFocus", "type": "WAF"},
    {"name": "Citrix NetScaler", "headers": {}, "body": r"Citrix NetScaler", "type": "WAF"},
    {"name": "Edgecast / Verizon", "headers": {"Server": r"ECD"}, "body": r"", "type": "CDN/WAF"},
    {"name": "Alibaba Cloud WAF", "headers": {"Server": r"aliyun"}, "body": r"", "type": "WAF"},
    {"name": "Tencent Cloud WAF", "headers": {"Server": r"TencentWAF"}, "body": r"", "type": "WAF"},
    {"name": "Baidu Cloud WAF", "headers": {}, "body": r"Baiduyun|百度云防护", "type": "WAF"},
    {"name": "UCloud", "headers": {}, "body": r"UCloud", "type": "WAF"},
]


class WAFDetectorModule:
    """Detects Web Application Firewalls from HTTP responses."""

    def __init__(self, config: dict):
        self.config = config.get("waf_detector", {})
        self.headers = {
            "User-Agent": config.get("recon", {}).get("user_agent", "BBAT/1.0")
        }
        self.timeout = self.config.get("timeout", 10)

    def detect(self, target: str) -> List[Dict]:
        """Detect WAF/CDN for a given URL."""
        from modules.utils import normalize_url
        url = normalize_url(target)
        findings = []
        try:
            resp = requests.get(url, headers=self.headers, timeout=self.timeout, verify=False)
            headers = {k.lower(): v for k, v in resp.headers.items()}
            body = resp.text

            for sig in WAF_SIGNATURES:
                detected = False
                confidence = "low"

                # Header checks (case-insensitive)
                for header_key, pattern in sig["headers"].items():
                    header_value = headers.get(header_key.lower(), "")
                    if pattern and re.search(pattern, header_value, re.IGNORECASE):
                        detected = True
                        confidence = "high"
                    elif header_value and not pattern:
                        detected = True
                        confidence = "medium"

                # Body check
                if sig["body"] and re.search(sig["body"], body, re.IGNORECASE):
                    detected = True
                    confidence = "high"

                if detected:
                    findings.append({
                        "waf": sig["name"],
                        "type": sig["type"],
                        "confidence": confidence,
                        "url": url,
                    })
        except requests.RequestException:
            pass

        # Deduplicate
        unique = []
        seen = set()
        for f in findings:
            key = f["waf"]
            if key not in seen:
                seen.add(key)
                unique.append(f)
        return unique

    def detect_batch(self, urls: List[str]) -> Dict:
        """Detect WAF/CDN for multiple URLs."""
        all_findings = []
        print(f"[*] Detecting WAF/CDN for {len(urls)} URLs...")
        for url in urls:
            findings = self.detect(url)
            all_findings.extend(findings)

        wafs = {f["waf"] for f in all_findings}
        types = {f["type"] for f in all_findings}
        print(f"[+] WAF detection complete. Detected {len(wafs)} unique WAFs/CDNs across {len(types)} categories.")
        return {
            "urls_checked": len(urls),
            "wafs_detected": list(wafs),
            "types_detected": list(types),
            "findings": all_findings,
        }
